name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: yarn run ci

      - run: yarn run lint

      - run: yarn run build

      - run: yarn run check-types
      - run: yarn run size
